version: "3.9"

services:
  negy-node-pool:
    build:
      context: .
      args:
        COMPONENT: node-pool
  negy-node1:
    build:
      context: .
      args:
        COMPONENT: node
    depends_on:
      - negy-node-pool
    command: --node-pool-endpoint http://negy-node-pool:3030 --port=3001
  negy-node2:
    build:
      context: .
      args:
        COMPONENT: node
    depends_on:
      - negy-node-pool
    command: --node-pool-endpoint http://negy-node-pool:3030 --port=3001
  negy-gateway:
    build:
      context: .
      args:
        COMPONENT: gateway
    depends_on:
      - negy-node-pool
    command: --node-pool-endpoint http://negy-node-pool:3030 --hops 2
    ports:
      - "127.0.0.1:3000:3000"
