name: cd

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Set up version
        run: echo "VERSION=$(head -n 3 Cargo.toml | tail -n 1 | sed -r 's/^.*\"(.*)\"$/\1/')" >> $GITHUB_ENV
      -
        name: Confirm version
        run: echo "version=${VERSION}"
      -
        name: Build and push node-pool
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/negy-node-pool:latest , ${{ secrets.DOCKER_HUB_USERNAME }}/negy-node-pool:${VERSION}
          build-args:
            COMPONENT=node-pool
      -
        name: Build and push node
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/negy-node:latest , ${{ secrets.DOCKER_HUB_USERNAME }}/negy-node:${VERSION}
          build-args:
            COMPONENT=node
      -
        name: Build and push gateway
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/negy-gateway:latest , ${{ secrets.DOCKER_HUB_USERNAME }}/negy-gateway:${VERSION}
          build-args:
            COMPONENT=gateway
